domain_tool/domaintool/domain_app/urls.py
from django.urls import path
from . import views
from .views import MyRestrictedView

urlpatterns = [
    path("", views.index, name="index"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("signin/", views.signin, name="signin"),
    path("logout/", views.signout, name="signout"),
    path("delete_company/<int:company_id>", views.company_delete, name="company_delete"),
    path("manage_companies/add_company", views.company_list, name="companies"),
    path("manage_companies/edit_company/<int:id>/", views.company_list, name="company_update"),
    path("manage_users/", views.list_users, name="users"),
    path("manage_companies/", views.companies, name="lists"),
    path("manage_domains/", views.domain, name="domain"),
    path("manage_domains/add_domain/",views.domain_list, name="domain_update"),
    path('lookup/', views.lookup, name='lookup'),
    path("domain_status/", views.domain_status, name='domain_status'),
    path("delete_domain/<int:domain_id>", views.domain_delete, name="domain_delete"),
    path('manage_users/add_user/', views.add_user, name='add_user'),
    path("manage_users/edit_user/<int:id>/", views.add_user, name="user_update"),
    path('inactive_account/', MyRestrictedView.as_view(), name='inactive_account'),
    path('update_domains_result/', views.update_domains, name='update_domains_result'),

]

domain_tool/domaintool/domaintool/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("domain_app.urls"))
]

domain_tool/domaintool/domain_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.utils import timezone

# Create your models here.
class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, username=None, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        user = self.create_user(email, password=password, **extra_fields)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    #username = models.CharField(max_length=30, blank=True, null=True, unique=False)
    username = models.CharField(max_length=30, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    # Your custom fields
    is_admin = models.BooleanField('Is admin', default=False)
    is_user = models.BooleanField('Is user', default=False)

    # Add any other custom fields specific to your application

    # Use the custom manager for managing users
    objects = CustomUserManager()

    # Set the email field as the unique identifier for authentication
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    
    def __str__(self):
        return self.email

class Company(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, blank=True, null=True)
    location = models.CharField(max_length=200)
    
    def __str__(self):
        return self.name
    
class Domain(models.Model):
    name = models.CharField(max_length=200)
    registration_date = models.DateTimeField(verbose_name="Date registered", null=True, blank=True)
    expiry_date = models.DateTimeField(verbose_name="Date of expiry", null=True, blank=True)
    registrar_name=models.CharField(max_length=300, null=True, blank=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, blank=True)

    def __str__(self):
        return self.name
    
class DomainInfo(models.Model):
    apiresponse = models.TextField()
    timestamp = models.DateTimeField()
    domain = models.ForeignKey(Domain, on_delete=models.CASCADE)
    
class Report(models.Model):
    title = models.CharField(max_length=200)
    report_date = models.DateField()
    report_generation_date = models.DateTimeField()
    generated_by = models.ForeignKey(User, on_delete=models.CASCADE)
    data = models.TextField()
    
    def __str__(self):
        return self.title
    
    

domain_tool/domaintool/domain_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Company, Domain
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from datetime import timedelta

User = get_user_model()

class UserForm(UserCreationForm):
    USER_TYPE_CHOICES = [
        ('admin', 'Admin'),
        ('user', 'User'),
    ]

    role = forms.ChoiceField(
        choices=USER_TYPE_CHOICES,
        widget=forms.RadioSelect,
        label='User Roles',
    )

    status = forms.BooleanField(
        initial=True,
        required=False,
        label='Active',
        widget=forms.CheckboxInput,
    )

    class Meta:
        model = get_user_model()  # Use get_user_model to ensure compatibility with custom user models
        fields = ['email', 'username', 'password1']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields.pop('password2')
        self.fields['password1'].help_text = ""
    
    def clean_username(self):
        username = self.cleaned_data['username']
        user_pk = self.instance.pk
        if User.objects.filter(username=username).exclude(pk=user_pk).exists():
            raise forms.ValidationError(_('This username is already in use.'))
        return username

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_admin = self.cleaned_data['role'] == 'admin'
        user.is_user = self.cleaned_data['role'] == 'user'
        user.is_active = self.cleaned_data['status']
        if commit:
            user.save()
        return user
        

class CompanyForm(forms.ModelForm):
    
    class Meta:
        model = Company
        fields = '__all__'
        labels = {
            'name': 'Company Name',
            'address': 'Company Address',
            'location': 'Company Location',
        }
        

class DomainForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['company'].error_messages = {'required': 'Please specify the company.'}


    class Meta:
        model = Domain
        fields = '__all__'
        labels = {
            'name': 'Domain Name',
            'registration_date': 'Date of Registration',
            'expiry_date': 'Date of Expiry',
            'company': 'Belongs To(Company):',
            'registrar_name': 'Registrar Name',
        }

domain_tool/domaintool/domain_app/views.py
from django.http import JsonResponse, HttpRequest, HttpResponseRedirect
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import CompanyForm, DomainForm, UserForm
from django.utils.html import format_html
from .models import Company, Domain
from django.db.models import Q
from django.views import View
import requests, json, logging
from django.contrib import messages
from django.core.mail import EmailMessage
from django.utils import timezone
from datetime import date,datetime, timedelta
from .models import User
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
import json
from django.views.decorators.http import require_POST
import time
import schedule
# Create your views here.

def index(request):
    
    return render(request, "index.html")

def copyright(request):
    current_year = datetime.datetime.now().year
    context = {
        'current_year': current_year
    }
    template_names = ['dashboard.html', 'base_dash.html']  # List of template names
    return render(request, template_names, context)

@login_required(login_url="signin")
def dashboard(request):
    active_domains = Domain.objects.filter(expiry_date__gte=date.today()).count()
    expired_domains = Domain.objects.filter(expiry_date__lt=date.today()).count()

    context = {
        'active_domains': active_domains,
        'expired_domains': expired_domains,
        'domains': Domain.objects.all(),
    }

    return render(request, 'dashboard.html', context)

def base_domain_tbl(request):
    domains = Domain.objects.all()
    print(domains) 
    context = {'domains': domains}
    return render(request, 'base_dash.html', context)


def signin(request):
    msg = ""
    if request.method == "POST":
        email = request.POST.get('email')
        password = request.POST.get('password')

        # Check if the user exists with the given email
        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            user = None

        # Check if the user exists and is not active
        if user and not user.is_active:
            msg = "Account inactive! Contact admin"
        else:
            # Attempt to authenticate the user
            user = authenticate(request, username=email, password=password)

            # Check if authentication was successful and user is active
            if user and user.is_active:
                # Print all fields of the user
                login(request, user)

                if "next" in request.POST:
                    return redirect(request.POST.get("next"))
                return redirect("dashboard")
            else:
                msg = "Invalid credentials"

    context = {"msg": msg}
    return render(request, "signin.html", context)

def signout(request):
    logout(request)
    return redirect("index")

def list_users(request):
    users = User.objects.all()
    
    threshold_date = timezone.now() + timedelta(days=30)

    # Query the database for domains with expiry date less than or equal to 30 days
    expiring_domains = Domain.objects.filter(expiry_date__lte=threshold_date)

    # Count the number of expiring domains
    domain_count = expiring_domains.count()
    
    now = timezone.now()
    for domain in expiring_domains:
        domain.remaining_days = (domain.expiry_date - now).days

    # Pass the data to the template
    context = {
        'domain_count': domain_count,
        'expiring_domains': expiring_domains,
        'users': users,
        'now': now
    }
    return render(request, 'users_list.html', context)

@login_required(login_url="signin")
def add_user(request, id=0):
    threshold_date = timezone.now() + timedelta(days=30)

    # Query the database for domains with expiry date less than or equal to 30 days
    expiring_domains = Domain.objects.filter(expiry_date__lte=threshold_date)

    # Count the number of expiring domains
    domain_count = expiring_domains.count()
    
    now = timezone.now()
    for domain in expiring_domains:
        domain.remaining_days = (domain.expiry_date - now).days
        
    if request.method == "GET":
        if id == 0:
            form = UserForm()
        else:
            user = get_object_or_404(User, pk=id)
            form = UserForm(instance=user)
        return render(request, "add_user.html", {'form': form})
    else:
        if id == 0:
            form = UserForm(request.POST)
        else:
            user = get_object_or_404(User, pk=id)
            form = UserForm(request.POST, instance=user)
        
        if form.is_valid():
            form.save()
            if id == 0:
                success_message = 'User Added!'
            else:
                success_message = 'User Updated!'
            # Add success message using Django's messages framework
            messages.success(request, success_message)
            users = User.objects.all()
            context = {'users': users}
            return render(request, "users_list.html", context)
        else:
            # Handle the case when the form is not valid
            return render(request, "add_user.html", {'form': form, 'domain_count': domain_count, 'expiring_domains': expiring_domains, 'now': now})

@login_required(login_url="signin")
def company_list(request, id=0):    
    threshold_date = timezone.now() + timedelta(days=30)

    # Query the database for domains with expiry date less than or equal to 30 days
    expiring_domains = Domain.objects.filter(expiry_date__lte=threshold_date)

    # Count the number of expiring domains
    domain_count = expiring_domains.count()
    
    now = timezone.now()
    for domain in expiring_domains:
        domain.remaining_days = (domain.expiry_date - now).days

    # Pass the data to the template
    context = {
        'domain_count': domain_count,
        'expiring_domains': expiring_domains,
        'now': now,
    } 
    if request.method == "GET":
        if id==0:
            form = CompanyForm()
        else:
            company = Company.objects.get(pk=id)
            form = CompanyForm(instance=company)
        return render(request, "manage_company.html",{'form':form,'domain_count': domain_count,'expiring_domains': expiring_domains, 'now': now, })
    else:
        if id == 0:
            form = CompanyForm(request.POST)
        else:
            company = Company.objects.get(pk=id)   
            form = CompanyForm(request.POST,instance=company) 
        if form.is_valid():
            form.save()
            messages.success(request, 'Company Added!')
            context = {'companies': Company.objects.all()}
        return render(request, "company_list.html", {'domain_count': domain_count,'expiring_domains': expiring_domains, 'now': now, 'companies': Company.objects.all()})


@login_required(login_url="signin")
def company_list(request, id=0):
              
    threshold_date = timezone.now() + timedelta(days=30)

    # Query the database for domains with expiry date less than or equal to 30 days
    expiring_domains = Domain.objects.filter(expiry_date__lte=threshold_date)

    # Count the number of expiring domains
    domain_count = expiring_domains.count()
    
    now = timezone.now()
    for domain in expiring_domains:
        domain.remaining_days = (domain.expiry_date - now).days

    if request.method == "GET":
        if id == 0:
            form = CompanyForm()
        else:
            company = get_object_or_404(Company, pk=id)
            form = CompanyForm(instance=company)
        return render(request, "manage_company.html", {'form': form, 'domain_count': domain_count, 'expiring_domains': expiring_domains, 'now': now})
    else:
        if id == 0:
            form = CompanyForm(request.POST)
        else:
            company = get_object_or_404(Company, pk=id)
            form = CompanyForm(request.POST, instance=company)

        if form.is_valid():
            form.save()
            if id == 0:
                success_message = 'Company Added!'
            else:
                success_message = 'Company Updated!'
            # Add success message using Django's messages framework
            messages.success(request, success_message)
            context = {'companies': Company.objects.all()}
            return render(request, "company_list.html", {'domain_count': domain_count, 'expiring_domains': expiring_domains, 'now': now, 'companies': Company.objects.all()})
    
@login_required(login_url="signin")
def companies(request):
    threshold_date = timezone.now() + timedelta(days=30)

    # Query the database for domains with expiry date less than or equal to 30 days
    expiring_domains = Domain.objects.filter(expiry_date__lte=threshold_date)

    # Count the number of expiring domains
    domain_count = expiring_domains.count()
    
    now = timezone.now()
    for domain in expiring_domains:
        domain.remaining_days = (domain.expiry_date - now).days

    # Pass the data to the template
    context = {
        'domain_count': domain_count,
        'expiring_domains': expiring_domains,
        'now': now,
        'companies': Company.objects.all()
    }
     
    return render(request,"company_list.html", context)

def company_delete(request, company_id):
    company = get_object_or_404(Company, pk=company_id)
    if request.method == 'POST':
        company.delete()
        messages.error(request, 'Company deleted!')
        return redirect('lists')  # Redirect to the appropriate URL after deletion

    # Optionally, you can provide a response here for other HTTP methods
    return redirect('lists')

@login_required(login_url="signin")
def domain(request):

domain_tool/domaintool/domain_app/templates/add_domain.html
{% extends 'base_dash.html' %}
{% load static %}

{% comment %} {% block notification %}
<li class="nav-item dropdown">
    <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-bell" style="color:white; font-size:20px;"></i>
        <span class="badge badge-warning navbar-badge" id="domainCountBadge">{{ domain_count }}</span>
    </a>
    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <span class="dropdown-item dropdown-header">Domains due expiry</span>
        <div class="dropdown-divider"></div>
        
        <!-- Dynamically generate dropdown items for each domain with days to expiry -->
        <div id="domainDropdownItems">
            {% for domain in expiring_domains %}
            <a href="#" class="dropdown-item">
                <i class="far fa-circle mr-2"></i>{{ domain.name }}
                <span class="float-right text-muted text-sm">{{ domain.remaining_days }} days</span>
            </a>
            {% endfor %}
        </div>
        
        <div class="dropdown-divider"></div>
    </div>
</li>
{% endblock %} {% endcomment %}

{% block content %}
 <!--preloader-->
 <div class="preloader-container" style="display: none">
    <div class="spinner"></div>
</div>
<style>
    .preloader-container {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: rgba(255, 255, 255, 0.8); /* semi-transparent white background */
        display: flex;
        align-items: center;
        justify-content: center;
        z-index: 1000;
    }

    .spinner {
        border: 4px solid rgba(0, 0, 0, 0.1);
        border-radius: 50%;
        border-top: 4px solid #3498db;
        width: 50px;
        height: 50px;
        animation: spin 1s linear infinite;
    }

    @keyframes spin {
        0% { transform: rotate(0deg); }
        100% { transform: rotate(360deg); }
    }

    .ajs-success {
        background-color: #4CAF50; 
        color: #ffffff;
    }
</style>
<div class="col-lg-10 mx-5">
<div class="jumbotron">
    <h3 class="display-6">Add Domain</h3>
    <hr class="my-4">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <form id="domainForm" action="" method="post" autocomplete="off">
        {% csrf_token %}
        {% load crispy_forms_tags %}
        <div class="row">
            <div class="col-md-4">
                {{ form.name|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.registrar_name|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.company|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.registration_date|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.expiry_date|as_crispy_field }}
            </div>
            <div class="col-md-4" style="margin-top: 32px;">
                <button type="button" class="btn btn-primary btn-block" id="lookupButton">
                    <i class="fas fa-search"></i> Lookup
                </button>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                <button type="submit" class="btn btn-success btn-block btn-lg"><i class="fa fa-database"
                        aria-hidden="true"></i> Submit</button>
            </div>
            <div class="col-md-4">
                <a href="{% url 'domain' %}" class="btn btn-secondary btn-block btn-lg">
                    <i class="fas fa-arrow-left"></i> Back to Domain List
                </a>
            </div>
        </div>
    </form>
</div>
</div>

{% endblock content %}

{% block js %}
<script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
<script>
    function validateForm() {
        var companyField = document.getElementById('id_company'); // Assuming the ID of your company field is 'id_company'
        if (!companyField.value.trim()) {
            alert('Please fill in the company field.');
            return false; // Prevent form submission
        }
        return true; // Allow form submission
    }

    document.addEventListener('DOMContentLoaded', function() {
        document.getElementById('domainForm').addEventListener('submit', function(event) {
            if (!validateForm()) {
                event.preventDefault(); // Prevent form submission if validation fails
            }
        });
    });
    
    document.getElementById('lookupButton').addEventListener('click', function (event) {
        showPreloader();

        // Simulate form submission delay with setTimeout
        setTimeout(function () {
            hidePreloader();
            // Add logic to handle the form submission, e.g., send data to the server
            // You can use AJAX, fetch, or other methods for actual form submission
            console.log('Form submitted!');
        }, 3000); // Adjust the timeout value as needed
    });

    function showPreloader() {
        var preloader = document.querySelector('.preloader-container');
        preloader.style.display = 'flex';
    }

    function hidePreloader() {
        var preloader = document.querySelector('.preloader-container');
        preloader.style.display = 'none';

        // Stop the spinner by removing the 'spin' animation class
        var spinner = document.querySelector('.spinner');
        spinner.classList.remove('spin');
    }

    // The rest of your scripts here
    // Set the position for Alertify.js notifications
    alertify.set('notifier', 'position', 'top-right');
    $(document).ready(function () {
        // Attach a click event listener to the Lookup button
        $('#lookupButton').click(function () {
            // Make an AJAX request to the Django view
            $.ajax({
                url: '{% url "lookup" %}',
                method: 'POST',
                data: $('#domainForm').serialize(),
                success: function (data) {
                    console.log('API Response:', data);
        
                    if (data.status === 'success') {
                        const registrationDate = data.registration_date;
                        const expirationDate = data.expiry_date;
                        const registrarName = data.registrar_name;
                    
                        console.log('Registration Date:', registrationDate);
                        console.log('Expiration Date:', expirationDate);
                        console.log('Registrar Name:', registrarName);
                    
                        if (registrationDate !== '' && expirationDate !== '' && registrarName !== '') {
                            $('#id_registration_date').val(registrationDate);
                            $('#id_expiry_date').val(expirationDate);
                            $('#id_registrar_name').val(registrarName); // Set the value of registrar_name field
                    
                            // Use Alertify.js for success message
                            alertify.success('Domain Found!');
                        } else {
                            console.error('Error: Date or registrar name properties are empty in the API response.');
                            // Use Alertify.js for error message
                            alertify.error('Error: Date or registrar name properties are empty.');
                        }
                    } else {
                        console.error('Error:', data.message);
                        // Use Alertify.js for error message
                        alertify.error('Error: ' + data.message);
                    }
                },
                error: function (error) {
                    console.error('Error:', error.responseText);
                    // Use Alertify.js for error message
                    alertify.error('Error: ' + error.responseText);
                },
                complete: function () {
                    // This function will run regardless of success or error
                    hidePreloader();
                }
            });
        });
    });
</script>
{% endblock%}

domain_tool/domaintool/domain_app/templates/add_user.html
{% extends 'base_dash.html' %}

{% comment %} {% block notification %}
<li class="nav-item dropdown">
    <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-bell" style="color:white; font-size:20px;"></i>
        <span class="badge badge-warning navbar-badge" id="domainCountBadge">{{ domain_count }}</span>
    </a>
    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <span class="dropdown-item dropdown-header">Domains due expiry</span>
        <div class="dropdown-divider"></div>
        
        <!-- Dynamically generate dropdown items for each domain with days to expiry -->
        <div id="domainDropdownItems">
            {% for domain in expiring_domains %}
            <a href="#" class="dropdown-item">
                <i class="far fa-circle mr-2"></i>{{ domain.name }}
                <span class="float-right text-muted text-sm">{{ domain.remaining_days }} days</span>
            </a>
            {% endfor %}
        </div>
        
        <div class="dropdown-divider"></div>
    </div>
</li>
{% endblock %} {% endcomment %}

{% block content %}
<div class="col-lg-10 mx-5">
    <div class="jumbotron">
        <h3 class="display-6">Add New User</h3>
        <hr class="my-4">

       

        <form method="post" action="" autocomplete="off">
            {% csrf_token %}
            {% load crispy_forms_tags %}
            
            <div class="row">
                <div class="col-md-8">
                    {{ form.username|as_crispy_field }}
                </div>
                <div class="col-md-4">
                    {{ form.password1|as_crispy_field }}
                </div>
                <div class="col-md-8">
                    {{ form.email|as_crispy_field }}
                </div>
            </div>

            <!-- Render is_admin field with checkboxes -->
            <style>
                /* Adjust the selector based on the class or HTML structure applied by Crispy Forms */
                .normal-font-weight label,
                .normal-font-weight input {
                    font-weight: normal !important;
                }
                .bold-font-weight label,
                .bold-font-weight input {
                    font-weight: bold !important;
                }
            </style>            
            <label class="col-form-label">User Roles</label>
            <div class="form-group">
                <div class="col-md-2 normal-font-weight" style="display: inline-block; margin-right: 10px; margin-bottom: 10px;">
                    {{ form.role.0 }}
                </div>
                <div class="col-md-2 normal-font-weight" style="display: inline-block; margin-right: 10px; margin-bottom: 10px;">
                    {{ form.role.1 }}
                </div>
                <div class="col-md-2 bold-font-weight" style="display: inline-block; margin-right: 10px; margin-bottom: 10px;">
                    {{ form.status|as_crispy_field }}
                </div>
            </div>

            <div class="row">
                <div class="col-md-8">
                    <button type="submit" class="btn btn-success btn-block btn-lg"><i class="fa fa-database"
                            aria-hidden="true"></i> Submit</button>
                </div>
                <div class="col-md-4">
                    <a href="{% url 'users' %}" class="btn btn-secondary btn-block btn-lg">
                        <i class="fas fa-arrow-left"></i> Back to Users List
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    $('.role-radio').change(function () {
        if ($(this).is(':checked')) {
            // Uncheck other radio buttons with the same class
            $('.role-radio').not(this).prop('checked', false);
        }
    });
</script>
{% endblock content %}

domain_tool/domaintool/domain_app/templates/inactive.html
{% extends 'base.html' %}

{% block content %}


<!-- Header-->
<header class="py-4">
    <div class="container-fluid px-lg-5">
        <div class="p-1 p-lg-1 bg-light rounded-3 text-center">
            <div class="m-4 m-lg-5">
                <h1 class="display-4 fw-bold">User Inactive! Contact Administrator</h1>
                <div class="mx-auto" style="width: 500px; height: 350px;">
                    <script src="https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.mjs" type="module"></script>
                    <dotlottie-player src="https://lottie.host/a7ac5165-d4b4-4875-90b3-2891d277f587/hILT9n95Bq.json" background="transparent" speed="1" style="width: 100%; height: 100%;" direction="1" mode="normal" autoplay loop></dotlottie-player>
                </div>
            </div>
        </div>
    </div>
</header>




{% endblock content %}

domain_tool/domaintool/domain_app/templates/index.html
{% extends 'base.html' %}

{% block content %}


<!-- Header-->
<header class="py-4">
    <div class="container-fluid px-lg-5">
        <div class="p-1 p-lg-1 bg-light rounded-3 text-center">
            <div class="m-4 m-lg-5">
                <h1 class="display-4 fw-bold">Group Domain Management Tool</h1>
                <div class="mx-auto" style="width: 500px; height: 350px;">
                    <script src="https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.mjs" type="module"></script>
                    <dotlottie-player src="https://lottie.host/a7ac5165-d4b4-4875-90b3-2891d277f587/hILT9n95Bq.json" background="transparent" speed="1" style="width: 100%; height: 100%;" direction="1" mode="normal" autoplay loop></dotlottie-player>
                </div>
            </div>
        </div>
    </div>
</header>




{% endblock content %}